version: "2.2"
services:
  netgw:
    image: eduard93/myclass:latest
    build:
      context: dotnet
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 55556:55556
  iris:
    init: true
    image: eduard93/netdemo:latest
    build:
      context: iris
      dockerfile: Dockerfile
    ports:
      - 52773:52773
      - 51773:51773
